"""Build SQL UPDATE statements to attach step images to each Thai House game's teaching.

Reads:
  - content/images/_thaihouse_manifest.json (produced by apply_thaihouse_step_images.py)
  - An inline WALK_LENS dict (fetched once from Supabase)

Writes:
  - scripts/thaihouse_step_images.sql (one batch file with all UPDATE statements)
"""
from __future__ import annotations

import json
from pathlib import Path

from apply_thaihouse_step_images import (  # noqa: F401
    pick_step_indices,
    CAPTIONS,
)

ROOT = Path(__file__).resolve().parents[1]

# Walk/summary lengths as fetched from Supabase 2026-04-10
WALK_LENS: dict[str, tuple[int, int]] = {
    "5-minute-dungeon": (7, 7),
    "5-minute-mystery": (7, 7),
    "above-and-below": (14, 14),
    "azul": (7, 7),
    "betrayal-at-house-on-the-hill": (10, 10),
    "cant-stop": (6, 6),
    "cant-stop-korean": (6, 6),
    "carcassonne": (8, 8),
    "catan": (9, 9),
    "century-golem-edition": (9, 9),
    "century-golem-edition-endless-world": (6, 6),
    "clue": (6, 6),
    "codenames": (6, 6),
    "codenames-duet": (4, 4),
    "codenames-pictures-heirloom-edition": (7, 7),
    "dead-of-winter": (14, 14),
    "deception-murder-in-hong-kong": (8, 8),
    "dixit": (5, 5),
    "everdell": (14, 14),
    "everdell-pearlbrook": (8, 8),
    "exit-the-game-series": (6, 6),
    "exploding-kittens": (4, 4),
    "flamecraft": (6, 6),
    "king-of-tokyo": (6, 6),
    "love-letter": (6, 6),
    "machi-koro": (8, 8),
    "one-night-ultimate-werewolf": (4, 4),
    "pandemic": (13, 13),
    "quacks-of-quedlinburg": (12, 12),
    "risk-game-of-thrones": (7, 7),
    "root": (15, 15),
    "rummikub": (6, 6),
    "scattergories": (4, 4),
    "scythe": (12, 12),
    "secret-hitler": (8, 8),
    "seven-wonders": (10, 10),
    "sheriff-of-nottingham": (10, 10),
    "six-nimmt": (4, 4),
    "splendor": (8, 8),
    "spot-it": (6, 6),
    "sushi-go": (4, 4),
    "takenoko": (10, 10),
    "the-crew": (5, 5),
    "ticket-to-ride": (8, 8),
    "tokaido": (7, 7),
    "unlock-epic-adventures": (6, 6),
    "unlock-escape-adventures": (6, 6),
    "unlock-exotic-adventures": (6, 6),
    "unlock-game-adventures": (6, 6),
    "unlock-mystery-adventures": (6, 6),
    "unlock-mythic-adventures": (6, 6),
    "unlock-secret-adventures": (6, 6),
    "unlock-star-wars-escape-game": (6, 6),
    "unlock-timeless-adventures": (6, 6),
    "uno": (4, 4),
    "villainous": (10, 10),
    "wavelength": (4, 4),
    "welcome-to": (6, 6),
    "wingspan": (14, 14),
}


def sql_text(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def build_sql_for_game(game_id: str, files: list[str], walk_len: int, sum_len: int) -> str:
    if not files or walk_len == 0:
        return f"-- {game_id}: skipped ({len(files)} images, walk_len={walk_len})\n"

    walk_idx = pick_step_indices(len(files), walk_len)
    sum_idx = pick_step_indices(len(files), sum_len)

    lines = [f"-- {game_id}: {len(files)} images -> walk[{walk_len}] sum[{sum_len}]"]
    for i, img in enumerate(files):
        caption = CAPTIONS.get(i + 1, f"Setup view {i+1}")
        img_lit = sql_text(img)
        cap_lit = sql_text(caption)
        if i < len(walk_idx):
            step = walk_idx[i]
            lines.append(
                f"UPDATE games SET teaching = "
                f"jsonb_set(jsonb_set(teaching, '{{setup,walkthrough,{step},image}}', to_jsonb({img_lit}::text)), "
                f"'{{setup,walkthrough,{step},image_caption}}', to_jsonb({cap_lit}::text)) "
                f"WHERE game_id = '{game_id}';"
            )
        if i < len(sum_idx) and sum_len > 0:
            step = sum_idx[i]
            lines.append(
                f"UPDATE games SET teaching = "
                f"jsonb_set(teaching, '{{setup,summary,{step},image}}', to_jsonb({img_lit}::text)) "
                f"WHERE game_id = '{game_id}';"
            )
    return "\n".join(lines) + "\n\n"


def main():
    manifest_path = ROOT / "content" / "images" / "_thaihouse_manifest.json"
    manifest = json.loads(manifest_path.read_text())

    # Games whose teaching content is handled separately (synced from local JSON files)
    SKIP_IN_GENERIC = {"wingspan"}

    out = ["-- Thai House step image attachments", "-- Generated by build_thaihouse_sql.py", ""]
    for game_id, info in manifest.items():
        if game_id in SKIP_IN_GENERIC:
            out.append(f"-- {game_id}: handled separately via local JSON sync, SKIPPED")
            continue
        if game_id not in WALK_LENS:
            out.append(f"-- {game_id}: no walk_len data, SKIPPED")
            continue
        walk_len, sum_len = WALK_LENS[game_id]
        out.append(build_sql_for_game(game_id, info["files"], walk_len, sum_len))

    sql_path = ROOT / "scripts" / "thaihouse_step_images.sql"
    sql_path.write_text("\n".join(out))
    print(f"Wrote {sql_path} ({len(out)} lines)")


if __name__ == "__main__":
    main()
