#!/usr/bin/env python3
"""Merge new game metadata into existing content JSON files for 144 new games."""

import json
import os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Saved {path}")


# ============================================================
# 1. GAME TAGS
# ============================================================
tags_path = os.path.join(BASE, "content", "game-tags.json")
tags = load_json(tags_path)

new_tags = {
    "cant-stop": ["quick-play", "family-friendly", "competitive", "gateway-game"],
    "jaipur": ["great-for-2", "date-night", "quick-play", "competitive"],
    "seven-wonders-duel": ["great-for-2", "date-night", "competitive", "engine-building"],
    "santorini": ["great-for-2", "date-night", "family-friendly", "competitive"],
    "forbidden-island": ["family-friendly", "cooperative", "gateway-game", "quick-play"],
    "forbidden-desert": ["family-friendly", "cooperative", "gateway-game"],
    "camel-up": ["family-friendly", "party-night", "competitive", "quick-play"],
    "sequence": ["family-friendly", "competitive", "gateway-game"],
    "blokus": ["family-friendly", "competitive", "tile-laying", "gateway-game"],
    "unstable-unicorns": ["family-friendly", "party-night", "competitive", "quick-play"],
    "exploding-kittens": ["family-friendly", "party-night", "quick-play", "competitive"],
    "machi-koro": ["family-friendly", "gateway-game", "engine-building", "competitive"],
    "tokaido": ["family-friendly", "great-for-2", "gateway-game", "competitive"],
    "istanbul": ["great-for-2", "competitive", "engine-building"],
    "five-tribes": ["brain-burner", "competitive", "area-control"],
    "alhambra": ["family-friendly", "competitive", "tile-laying", "gateway-game"],
    "karuba": ["family-friendly", "competitive", "tile-laying", "quick-play"],
    "kingsburg": ["family-friendly", "competitive", "engine-building"],
    "stone-age": ["family-friendly", "gateway-game", "competitive", "engine-building"],
    "raiders-of-the-north-sea": ["competitive", "engine-building", "great-for-2"],
    "architects-of-the-west-kingdom": ["competitive", "engine-building", "brain-burner"],
    "paladins-of-the-west-kingdom": ["competitive", "engine-building", "brain-burner"],
    "champions-of-midgard": ["competitive", "engine-building", "narrative"],
    "clank-in-space": ["great-for-2", "deck-building", "competitive", "narrative"],
    "mysterium-park": ["family-friendly", "cooperative", "narrative", "quick-play"],
    "horrified": ["family-friendly", "cooperative", "gateway-game"],
    "unmatched": ["great-for-2", "date-night", "competitive", "area-control"],
    "dice-throne": ["great-for-2", "competitive", "quick-play"],
    "star-realms": ["great-for-2", "quick-play", "deck-building", "competitive"],
    "hero-realms": ["great-for-2", "quick-play", "deck-building", "competitive"],
    "res-arcana": ["great-for-2", "competitive", "engine-building"],
    "race-for-the-galaxy": ["solo-friendly", "great-for-2", "brain-burner", "engine-building", "competitive"],
    "roll-for-the-galaxy": ["solo-friendly", "great-for-2", "competitive", "engine-building"],
    "pandemic-legacy-season-1": ["cooperative", "narrative", "brain-burner"],
    "gloomhaven-jaws-of-the-lion": ["cooperative", "narrative", "brain-burner"],
    "mice-and-mystics": ["cooperative", "narrative", "family-friendly"],
    "descent-legends-of-the-dark": ["cooperative", "narrative", "brain-burner"],
    "mansions-of-madness": ["cooperative", "narrative", "brain-burner"],
    "arkham-horror-card-game": ["solo-friendly", "cooperative", "narrative", "deck-building", "brain-burner"],
    "marvel-champions": ["solo-friendly", "cooperative", "deck-building", "narrative"],
    "keyforge": ["great-for-2", "competitive", "deck-building"],
    "aeons-end": ["solo-friendly", "cooperative", "deck-building", "brain-burner"],
    "tiny-towns": ["family-friendly", "competitive", "tile-laying"],
    "calico": ["solo-friendly", "great-for-2", "family-friendly", "tile-laying", "competitive"],
    "cascadia": ["solo-friendly", "great-for-2", "family-friendly", "tile-laying", "competitive"],
    "harmonies": ["solo-friendly", "family-friendly", "tile-laying", "competitive"],
    "sky-team": ["great-for-2", "cooperative", "date-night"],
    "meadow": ["solo-friendly", "great-for-2", "family-friendly", "competitive"],
    "flamecraft": ["solo-friendly", "family-friendly", "engine-building", "competitive"],
    "my-city": ["family-friendly", "narrative", "tile-laying", "competitive"],
    "cryptid": ["brain-burner", "competitive", "area-control"],
    "deception-murder-in-hong-kong": ["party-night", "hidden-roles", "cooperative", "competitive"],
    "blood-on-the-clocktower": ["party-night", "hidden-roles", "narrative", "competitive"],
    "secret-hitler": ["party-night", "hidden-roles", "competitive"],
    "the-resistance-avalon": ["party-night", "hidden-roles", "quick-play", "competitive"],
    "werewords": ["party-night", "hidden-roles", "word-game", "quick-play"],
    "a-fake-artist-goes-to-new-york": ["party-night", "family-friendly", "hidden-roles", "quick-play"],
    "monikers": ["party-night", "family-friendly", "word-game"],
    "taboo": ["party-night", "family-friendly", "word-game", "quick-play"],
    "scattergories": ["party-night", "family-friendly", "word-game", "quick-play"],
    "apples-to-apples": ["party-night", "family-friendly", "quick-play", "competitive"],
    "what-do-you-meme": ["party-night", "competitive", "quick-play"],
    "cards-against-humanity": ["party-night", "competitive", "quick-play"],
    "jenga": ["family-friendly", "party-night", "quick-play", "competitive"],
    "connect-four": ["family-friendly", "great-for-2", "quick-play", "competitive"],
    "boggle": ["family-friendly", "quick-play", "word-game", "competitive"],
    "bananagrams": ["family-friendly", "quick-play", "word-game", "competitive"],
    "scrabble": ["family-friendly", "great-for-2", "word-game", "competitive"],
    "trivial-pursuit": ["party-night", "family-friendly", "competitive"],
    "clue": ["family-friendly", "hidden-roles", "competitive"],
    "monopoly": ["family-friendly", "competitive", "negotiation"],
    "risk": ["brain-burner", "area-control", "competitive", "negotiation"],
    "chess": ["great-for-2", "brain-burner", "competitive"],
    "checkers": ["family-friendly", "great-for-2", "quick-play", "competitive"],
    "backgammon": ["great-for-2", "competitive", "gateway-game"],
    "mahjong": ["brain-burner", "competitive", "tile-laying"],
    "cribbage": ["great-for-2", "competitive", "quick-play"],
    "gin-rummy": ["great-for-2", "competitive", "quick-play"],
    "uno": ["family-friendly", "party-night", "quick-play", "competitive"],
    "skip-bo": ["family-friendly", "competitive", "quick-play"],
    "phase-10": ["family-friendly", "competitive"],
    "ticket-to-ride-europe": ["great-for-2", "family-friendly", "gateway-game", "competitive"],
    "ticket-to-ride-nordic": ["great-for-2", "family-friendly", "gateway-game", "competitive"],
    "catan-seafarers": ["family-friendly", "gateway-game", "negotiation", "competitive"],
    "pandemic-hot-zone": ["great-for-2", "cooperative", "gateway-game", "quick-play"],
    "codenames-duet": ["great-for-2", "date-night", "cooperative", "word-game"],
    "sushi-go": ["family-friendly", "quick-play", "gateway-game", "competitive"],
    "love-letter-2019": ["quick-play", "date-night", "family-friendly", "hidden-roles", "competitive"],
    "the-mind": ["quick-play", "cooperative", "party-night"],
    "hanabi": ["cooperative", "quick-play", "brain-burner"],
    "point-salad": ["family-friendly", "quick-play", "competitive", "gateway-game"],
    "no-thanks": ["family-friendly", "quick-play", "competitive", "party-night"],
    "take-5": ["family-friendly", "quick-play", "competitive", "party-night"],
    "scout": ["quick-play", "competitive", "family-friendly"],
    "cockroach-poker": ["party-night", "family-friendly", "hidden-roles", "quick-play"],
    "fox-in-the-forest": ["great-for-2", "date-night", "quick-play", "competitive"],
    "hanamikoji": ["great-for-2", "date-night", "competitive"],
    "lost-cities-card-game": ["great-for-2", "date-night", "quick-play", "competitive"],
    "schotten-totten": ["great-for-2", "date-night", "competitive"],
    "onitama": ["great-for-2", "date-night", "quick-play", "competitive"],
    "hive": ["great-for-2", "competitive", "brain-burner"],
    "azul-summer-pavilion": ["great-for-2", "family-friendly", "tile-laying", "competitive"],
    "azul-stained-glass": ["great-for-2", "family-friendly", "tile-laying", "competitive"],
    "splendor-duel": ["great-for-2", "date-night", "competitive", "engine-building"],
    "century-eastern-wonders": ["great-for-2", "family-friendly", "engine-building", "competitive"],
    "imhotep": ["family-friendly", "competitive", "gateway-game"],
    "ethnos": ["family-friendly", "competitive", "area-control", "gateway-game"],
    "quest-for-el-dorado": ["family-friendly", "deck-building", "competitive", "gateway-game"],
    "downforce": ["family-friendly", "competitive", "gateway-game"],
    "flamme-rouge": ["family-friendly", "competitive", "gateway-game"],
    "jamaica": ["family-friendly", "competitive", "gateway-game"],
    "celestia": ["family-friendly", "party-night", "quick-play", "competitive"],
    "treasure-island": ["family-friendly", "competitive", "narrative"],
    "survive-escape-from-atlantis": ["family-friendly", "competitive", "area-control"],
    "king-of-new-york": ["family-friendly", "quick-play", "competitive", "area-control"],
    "bunny-kingdom": ["family-friendly", "competitive", "area-control"],
    "isle-of-cats": ["family-friendly", "competitive", "tile-laying"],
    "nidavellir": ["competitive", "engine-building", "gateway-game"],
    "its-a-wonderful-world": ["solo-friendly", "competitive", "engine-building"],
    "gizmos": ["solo-friendly", "family-friendly", "engine-building", "competitive"],
    "space-base": ["family-friendly", "engine-building", "competitive"],
    "cubitos": ["family-friendly", "competitive", "engine-building"],
    "quartz": ["family-friendly", "quick-play", "competitive"],
    "libertalia-winds-of-galecrest": ["competitive", "hidden-roles", "gateway-game"],
    "forgotten-waters": ["party-night", "cooperative", "narrative"],
    "nemesis": ["cooperative", "narrative", "brain-burner"],
    "eclipse-second-dawn": ["brain-burner", "competitive", "area-control", "engine-building"],
    "twilight-imperium-4": ["brain-burner", "competitive", "area-control", "negotiation"],
    "terra-mystica": ["brain-burner", "competitive", "area-control", "engine-building"],
    "gaia-project": ["solo-friendly", "brain-burner", "competitive", "area-control", "engine-building"],
    "feast-for-odin": ["solo-friendly", "brain-burner", "competitive", "engine-building"],
    "le-havre": ["solo-friendly", "brain-burner", "competitive", "engine-building"],
    "ora-et-labora": ["brain-burner", "competitive", "engine-building"],
    "caverna": ["solo-friendly", "brain-burner", "competitive", "engine-building"],
    "clans-of-caledonia": ["brain-burner", "competitive", "engine-building", "area-control"],
    "barrage": ["brain-burner", "competitive", "engine-building", "area-control"],
    "kanban-ev": ["brain-burner", "competitive", "engine-building"],
    "lisboa": ["brain-burner", "competitive", "engine-building"],
    "the-gallerist": ["brain-burner", "competitive", "engine-building"],
    "anachrony": ["brain-burner", "competitive", "engine-building", "area-control"],
    "maracaibo": ["brain-burner", "competitive", "engine-building", "narrative"],
    "dune-imperium": ["solo-friendly", "competitive", "deck-building", "area-control", "engine-building"],
    "oath": ["brain-burner", "competitive", "area-control", "narrative"],
    "sleeping-gods": ["solo-friendly", "cooperative", "narrative", "brain-burner"],
}

tags.update(new_tags)
save_json(tags_path, tags)
non_meta = [k for k in tags if k != "_meta"]
print(f"  game-tags.json: {len(non_meta)} games")


# ============================================================
# 2. MSRP PRICES
# ============================================================
prices_path = os.path.join(BASE, "content", "msrp-prices.json")
prices = load_json(prices_path)

new_prices = {
    "cant-stop": 29.99, "jaipur": 24.99, "seven-wonders-duel": 29.99, "santorini": 29.99,
    "forbidden-island": 19.99, "forbidden-desert": 24.99, "camel-up": 44.99, "sequence": 14.99,
    "blokus": 29.99, "unstable-unicorns": 19.99, "exploding-kittens": 19.99, "machi-koro": 29.99,
    "tokaido": 39.99, "istanbul": 49.99, "five-tribes": 59.99, "alhambra": 34.99,
    "karuba": 34.99, "kingsburg": 49.99, "stone-age": 59.99, "raiders-of-the-north-sea": 49.99,
    "architects-of-the-west-kingdom": 49.99, "paladins-of-the-west-kingdom": 59.99,
    "champions-of-midgard": 59.99, "clank-in-space": 64.99, "mysterium-park": 29.99,
    "horrified": 34.99, "unmatched": 29.99, "dice-throne": 29.99, "star-realms": 14.99,
    "hero-realms": 14.99, "res-arcana": 39.99, "race-for-the-galaxy": 34.99,
    "roll-for-the-galaxy": 59.99, "pandemic-legacy-season-1": 69.99,
    "gloomhaven-jaws-of-the-lion": 49.99, "mice-and-mystics": 79.99,
    "descent-legends-of-the-dark": 174.99, "mansions-of-madness": 99.99,
    "arkham-horror-card-game": 44.99, "marvel-champions": 44.99, "keyforge": 9.99,
    "aeons-end": 39.99, "tiny-towns": 44.99, "calico": 44.99, "cascadia": 44.99,
    "harmonies": 44.99, "sky-team": 29.99, "meadow": 49.99, "flamecraft": 59.99,
    "my-city": 34.99, "cryptid": 29.99, "deception-murder-in-hong-kong": 39.99,
    "blood-on-the-clocktower": 59.99, "secret-hitler": 35.00, "the-resistance-avalon": 19.99,
    "werewords": 19.99, "a-fake-artist-goes-to-new-york": 19.99, "monikers": 29.99,
    "taboo": 19.99, "scattergories": 14.99, "apples-to-apples": 19.99,
    "what-do-you-meme": 29.99, "cards-against-humanity": 25.00, "jenga": 14.99,
    "connect-four": 9.99, "boggle": 14.99, "bananagrams": 14.99, "scrabble": 19.99,
    "trivial-pursuit": 29.99, "clue": 14.99, "monopoly": 19.99, "risk": 29.99,
    "chess": 24.99, "checkers": 12.99, "backgammon": 24.99, "mahjong": 39.99,
    "cribbage": 12.99, "gin-rummy": 7.99, "uno": 5.99, "skip-bo": 9.99, "phase-10": 9.99,
    "ticket-to-ride-europe": 54.99, "ticket-to-ride-nordic": 44.99, "catan-seafarers": 54.99,
    "pandemic-hot-zone": 19.99, "codenames-duet": 19.99, "sushi-go": 12.99,
    "love-letter-2019": 14.99, "the-mind": 14.99, "hanabi": 12.99, "point-salad": 19.99,
    "no-thanks": 12.99, "take-5": 12.99, "scout": 19.99, "cockroach-poker": 12.99,
    "fox-in-the-forest": 14.99, "hanamikoji": 19.99, "lost-cities-card-game": 14.99,
    "schotten-totten": 19.99, "onitama": 29.99, "hive": 29.99, "azul-summer-pavilion": 44.99,
    "azul-stained-glass": 44.99, "splendor-duel": 29.99, "century-eastern-wonders": 39.99,
    "imhotep": 39.99, "ethnos": 39.99, "quest-for-el-dorado": 44.99, "downforce": 44.99,
    "flamme-rouge": 49.99, "jamaica": 49.99, "celestia": 34.99, "treasure-island": 49.99,
    "survive-escape-from-atlantis": 34.99, "king-of-new-york": 44.99, "bunny-kingdom": 49.99,
    "isle-of-cats": 49.99, "nidavellir": 39.99, "its-a-wonderful-world": 44.99,
    "gizmos": 44.99, "space-base": 44.99, "cubitos": 49.99, "quartz": 29.99,
    "libertalia-winds-of-galecrest": 59.99, "forgotten-waters": 59.99, "nemesis": 139.99,
    "eclipse-second-dawn": 149.99, "twilight-imperium-4": 149.99, "terra-mystica": 79.99,
    "gaia-project": 99.99, "feast-for-odin": 99.99, "le-havre": 69.99,
    "ora-et-labora": 89.99, "caverna": 89.99, "clans-of-caledonia": 69.99,
    "barrage": 89.99, "kanban-ev": 79.99, "lisboa": 79.99, "the-gallerist": 79.99,
    "anachrony": 89.99, "maracaibo": 79.99, "dune-imperium": 49.99, "oath": 89.99,
    "sleeping-gods": 99.99,
}

prices.update(new_prices)
save_json(prices_path, prices)
print(f"  msrp-prices.json: {len(prices)} games")


# ============================================================
# 3. BGG METADATA
# ============================================================
bgg_path = os.path.join(BASE, "content", "bgg-metadata.json")
bgg = load_json(bgg_path)

new_bgg = {
    "cant-stop": {"bgg_rating": 7.0, "bgg_weight": 1.41, "bgg_rank": 726, "num_ratings": 18500},
    "jaipur": {"bgg_rating": 7.4, "bgg_weight": 1.49, "bgg_rank": 104, "num_ratings": 87000},
    "seven-wonders-duel": {"bgg_rating": 8.1, "bgg_weight": 2.23, "bgg_rank": 15, "num_ratings": 115000},
    "santorini": {"bgg_rating": 7.4, "bgg_weight": 1.71, "bgg_rank": 275, "num_ratings": 45000},
    "forbidden-island": {"bgg_rating": 6.8, "bgg_weight": 1.74, "bgg_rank": 685, "num_ratings": 72000},
    "forbidden-desert": {"bgg_rating": 7.2, "bgg_weight": 2.03, "bgg_rank": 296, "num_ratings": 58000},
    "camel-up": {"bgg_rating": 7.0, "bgg_weight": 1.5, "bgg_rank": 520, "num_ratings": 38000},
    "sequence": {"bgg_rating": 6.1, "bgg_weight": 1.25, "bgg_rank": 4200, "num_ratings": 11000},
    "blokus": {"bgg_rating": 7.0, "bgg_weight": 1.73, "bgg_rank": 580, "num_ratings": 48000},
    "unstable-unicorns": {"bgg_rating": 6.2, "bgg_weight": 1.41, "bgg_rank": 2950, "num_ratings": 15000},
    "exploding-kittens": {"bgg_rating": 6.0, "bgg_weight": 1.11, "bgg_rank": 3800, "num_ratings": 62000},
    "machi-koro": {"bgg_rating": 6.6, "bgg_weight": 1.52, "bgg_rank": 1520, "num_ratings": 42000},
    "tokaido": {"bgg_rating": 7.0, "bgg_weight": 1.73, "bgg_rank": 490, "num_ratings": 53000},
    "istanbul": {"bgg_rating": 7.6, "bgg_weight": 2.59, "bgg_rank": 114, "num_ratings": 62000},
    "five-tribes": {"bgg_rating": 7.8, "bgg_weight": 2.86, "bgg_rank": 95, "num_ratings": 68000},
    "alhambra": {"bgg_rating": 7.0, "bgg_weight": 2.12, "bgg_rank": 625, "num_ratings": 44000},
    "karuba": {"bgg_rating": 7.0, "bgg_weight": 1.64, "bgg_rank": 945, "num_ratings": 16000},
    "kingsburg": {"bgg_rating": 7.2, "bgg_weight": 2.42, "bgg_rank": 570, "num_ratings": 27000},
    "stone-age": {"bgg_rating": 7.6, "bgg_weight": 2.49, "bgg_rank": 132, "num_ratings": 75000},
    "raiders-of-the-north-sea": {"bgg_rating": 7.7, "bgg_weight": 2.4, "bgg_rank": 105, "num_ratings": 62000},
    "architects-of-the-west-kingdom": {"bgg_rating": 7.9, "bgg_weight": 2.69, "bgg_rank": 72, "num_ratings": 58000},
    "paladins-of-the-west-kingdom": {"bgg_rating": 8.0, "bgg_weight": 3.51, "bgg_rank": 90, "num_ratings": 32000},
    "champions-of-midgard": {"bgg_rating": 7.5, "bgg_weight": 2.51, "bgg_rank": 215, "num_ratings": 42000},
    "clank-in-space": {"bgg_rating": 7.7, "bgg_weight": 2.35, "bgg_rank": 168, "num_ratings": 36000},
    "mysterium-park": {"bgg_rating": 7.2, "bgg_weight": 1.51, "bgg_rank": 745, "num_ratings": 18000},
    "horrified": {"bgg_rating": 7.5, "bgg_weight": 2.03, "bgg_rank": 242, "num_ratings": 35000},
    "unmatched": {"bgg_rating": 7.7, "bgg_weight": 1.91, "bgg_rank": 165, "num_ratings": 28000},
    "dice-throne": {"bgg_rating": 7.5, "bgg_weight": 1.77, "bgg_rank": 245, "num_ratings": 24000},
    "star-realms": {"bgg_rating": 7.5, "bgg_weight": 1.95, "bgg_rank": 153, "num_ratings": 52000},
    "hero-realms": {"bgg_rating": 7.4, "bgg_weight": 1.92, "bgg_rank": 285, "num_ratings": 30000},
    "res-arcana": {"bgg_rating": 7.6, "bgg_weight": 2.51, "bgg_rank": 155, "num_ratings": 28000},
    "race-for-the-galaxy": {"bgg_rating": 7.7, "bgg_weight": 2.98, "bgg_rank": 78, "num_ratings": 83000},
    "roll-for-the-galaxy": {"bgg_rating": 7.5, "bgg_weight": 2.77, "bgg_rank": 185, "num_ratings": 42000},
    "pandemic-legacy-season-1": {"bgg_rating": 8.6, "bgg_weight": 2.84, "bgg_rank": 4, "num_ratings": 155000},
    "gloomhaven-jaws-of-the-lion": {"bgg_rating": 8.3, "bgg_weight": 3.31, "bgg_rank": 24, "num_ratings": 52000},
    "mice-and-mystics": {"bgg_rating": 7.2, "bgg_weight": 2.66, "bgg_rank": 450, "num_ratings": 32000},
    "descent-legends-of-the-dark": {"bgg_rating": 7.4, "bgg_weight": 3.35, "bgg_rank": 395, "num_ratings": 12000},
    "mansions-of-madness": {"bgg_rating": 7.8, "bgg_weight": 2.97, "bgg_rank": 82, "num_ratings": 58000},
    "arkham-horror-card-game": {"bgg_rating": 8.2, "bgg_weight": 3.33, "bgg_rank": 20, "num_ratings": 72000},
    "marvel-champions": {"bgg_rating": 8.1, "bgg_weight": 2.72, "bgg_rank": 35, "num_ratings": 52000},
    "keyforge": {"bgg_rating": 7.1, "bgg_weight": 2.35, "bgg_rank": 780, "num_ratings": 19000},
    "aeons-end": {"bgg_rating": 7.9, "bgg_weight": 2.78, "bgg_rank": 88, "num_ratings": 38000},
    "tiny-towns": {"bgg_rating": 7.3, "bgg_weight": 1.78, "bgg_rank": 375, "num_ratings": 32000},
    "calico": {"bgg_rating": 7.4, "bgg_weight": 1.88, "bgg_rank": 295, "num_ratings": 35000},
    "cascadia": {"bgg_rating": 7.9, "bgg_weight": 1.87, "bgg_rank": 48, "num_ratings": 75000},
    "harmonies": {"bgg_rating": 7.8, "bgg_weight": 2.05, "bgg_rank": 125, "num_ratings": 18000},
    "sky-team": {"bgg_rating": 8.0, "bgg_weight": 2.08, "bgg_rank": 58, "num_ratings": 28000},
    "meadow": {"bgg_rating": 7.5, "bgg_weight": 2.16, "bgg_rank": 285, "num_ratings": 22000},
    "flamecraft": {"bgg_rating": 7.5, "bgg_weight": 2.21, "bgg_rank": 265, "num_ratings": 24000},
    "my-city": {"bgg_rating": 7.5, "bgg_weight": 1.79, "bgg_rank": 325, "num_ratings": 20000},
    "cryptid": {"bgg_rating": 7.3, "bgg_weight": 2.06, "bgg_rank": 385, "num_ratings": 26000},
    "deception-murder-in-hong-kong": {"bgg_rating": 7.5, "bgg_weight": 1.67, "bgg_rank": 175, "num_ratings": 42000},
    "blood-on-the-clocktower": {"bgg_rating": 8.6, "bgg_weight": 2.32, "bgg_rank": 11, "num_ratings": 35000},
    "secret-hitler": {"bgg_rating": 7.5, "bgg_weight": 1.62, "bgg_rank": 218, "num_ratings": 68000},
    "the-resistance-avalon": {"bgg_rating": 7.6, "bgg_weight": 1.63, "bgg_rank": 140, "num_ratings": 85000},
    "werewords": {"bgg_rating": 7.0, "bgg_weight": 1.22, "bgg_rank": 820, "num_ratings": 12000},
    "a-fake-artist-goes-to-new-york": {"bgg_rating": 7.2, "bgg_weight": 1.14, "bgg_rank": 550, "num_ratings": 14000},
    "monikers": {"bgg_rating": 7.5, "bgg_weight": 1.12, "bgg_rank": 305, "num_ratings": 16000},
    "taboo": {"bgg_rating": 6.5, "bgg_weight": 1.05, "bgg_rank": 2450, "num_ratings": 9500},
    "scattergories": {"bgg_rating": 6.4, "bgg_weight": 1.11, "bgg_rank": 2850, "num_ratings": 10500},
    "apples-to-apples": {"bgg_rating": 6.2, "bgg_weight": 1.09, "bgg_rank": 3250, "num_ratings": 28000},
    "what-do-you-meme": {"bgg_rating": 6.0, "bgg_weight": 1.05, "bgg_rank": 6500, "num_ratings": 3200},
    "cards-against-humanity": {"bgg_rating": 6.3, "bgg_weight": 1.09, "bgg_rank": 2900, "num_ratings": 58000},
    "jenga": {"bgg_rating": 6.3, "bgg_weight": 1.02, "bgg_rank": 3100, "num_ratings": 14500},
    "connect-four": {"bgg_rating": 6.0, "bgg_weight": 1.18, "bgg_rank": 5200, "num_ratings": 11000},
    "boggle": {"bgg_rating": 6.5, "bgg_weight": 1.12, "bgg_rank": 2350, "num_ratings": 10000},
    "bananagrams": {"bgg_rating": 6.4, "bgg_weight": 1.15, "bgg_rank": 2750, "num_ratings": 13500},
    "scrabble": {"bgg_rating": 6.7, "bgg_weight": 1.86, "bgg_rank": 1680, "num_ratings": 34000},
    "trivial-pursuit": {"bgg_rating": 6.2, "bgg_weight": 1.63, "bgg_rank": 4100, "num_ratings": 10500},
    "clue": {"bgg_rating": 6.4, "bgg_weight": 1.51, "bgg_rank": 2950, "num_ratings": 25000},
    "monopoly": {"bgg_rating": 6.0, "bgg_weight": 1.68, "bgg_rank": 5800, "num_ratings": 44000},
    "risk": {"bgg_rating": 6.2, "bgg_weight": 2.08, "bgg_rank": 4500, "num_ratings": 38000},
    "chess": {"bgg_rating": 7.7, "bgg_weight": 3.69, "bgg_rank": 245, "num_ratings": 58000},
    "checkers": {"bgg_rating": 6.2, "bgg_weight": 1.79, "bgg_rank": 4800, "num_ratings": 9800},
    "backgammon": {"bgg_rating": 6.8, "bgg_weight": 2.06, "bgg_rank": 1450, "num_ratings": 13500},
    "mahjong": {"bgg_rating": 7.1, "bgg_weight": 2.79, "bgg_rank": 750, "num_ratings": 6500},
    "cribbage": {"bgg_rating": 7.0, "bgg_weight": 1.96, "bgg_rank": 810, "num_ratings": 12000},
    "gin-rummy": {"bgg_rating": 6.6, "bgg_weight": 1.76, "bgg_rank": 2250, "num_ratings": 5500},
    "uno": {"bgg_rating": 6.0, "bgg_weight": 1.15, "bgg_rank": 5950, "num_ratings": 25000},
    "skip-bo": {"bgg_rating": 6.2, "bgg_weight": 1.25, "bgg_rank": 4450, "num_ratings": 6800},
    "phase-10": {"bgg_rating": 6.1, "bgg_weight": 1.36, "bgg_rank": 4950, "num_ratings": 7500},
    "ticket-to-ride-europe": {"bgg_rating": 7.5, "bgg_weight": 1.92, "bgg_rank": 120, "num_ratings": 125000},
    "ticket-to-ride-nordic": {"bgg_rating": 7.4, "bgg_weight": 1.88, "bgg_rank": 485, "num_ratings": 15000},
    "catan-seafarers": {"bgg_rating": 7.2, "bgg_weight": 2.42, "bgg_rank": 475, "num_ratings": 38000},
    "pandemic-hot-zone": {"bgg_rating": 7.1, "bgg_weight": 1.82, "bgg_rank": 1250, "num_ratings": 5500},
    "codenames-duet": {"bgg_rating": 7.5, "bgg_weight": 1.31, "bgg_rank": 195, "num_ratings": 48000},
    "sushi-go": {"bgg_rating": 7.0, "bgg_weight": 1.17, "bgg_rank": 635, "num_ratings": 72000},
    "love-letter-2019": {"bgg_rating": 7.3, "bgg_weight": 1.24, "bgg_rank": 310, "num_ratings": 95000},
    "the-mind": {"bgg_rating": 7.0, "bgg_weight": 1.07, "bgg_rank": 595, "num_ratings": 48000},
    "hanabi": {"bgg_rating": 7.2, "bgg_weight": 1.71, "bgg_rank": 260, "num_ratings": 75000},
    "point-salad": {"bgg_rating": 7.1, "bgg_weight": 1.28, "bgg_rank": 585, "num_ratings": 35000},
    "no-thanks": {"bgg_rating": 7.0, "bgg_weight": 1.15, "bgg_rank": 645, "num_ratings": 38000},
    "take-5": {"bgg_rating": 6.9, "bgg_weight": 1.25, "bgg_rank": 880, "num_ratings": 28000},
    "scout": {"bgg_rating": 7.5, "bgg_weight": 1.67, "bgg_rank": 235, "num_ratings": 18000},
    "cockroach-poker": {"bgg_rating": 7.1, "bgg_weight": 1.1, "bgg_rank": 575, "num_ratings": 28000},
    "fox-in-the-forest": {"bgg_rating": 7.1, "bgg_weight": 1.48, "bgg_rank": 615, "num_ratings": 26000},
    "hanamikoji": {"bgg_rating": 7.4, "bgg_weight": 1.71, "bgg_rank": 265, "num_ratings": 24000},
    "lost-cities-card-game": {"bgg_rating": 7.1, "bgg_weight": 1.5, "bgg_rank": 485, "num_ratings": 52000},
    "schotten-totten": {"bgg_rating": 7.3, "bgg_weight": 1.75, "bgg_rank": 305, "num_ratings": 24000},
    "onitama": {"bgg_rating": 7.3, "bgg_weight": 1.71, "bgg_rank": 245, "num_ratings": 44000},
    "hive": {"bgg_rating": 7.3, "bgg_weight": 2.35, "bgg_rank": 185, "num_ratings": 48000},
    "azul-summer-pavilion": {"bgg_rating": 7.7, "bgg_weight": 2.16, "bgg_rank": 185, "num_ratings": 36000},
    "azul-stained-glass": {"bgg_rating": 7.5, "bgg_weight": 2.22, "bgg_rank": 295, "num_ratings": 28000},
    "splendor-duel": {"bgg_rating": 7.8, "bgg_weight": 2.03, "bgg_rank": 145, "num_ratings": 28000},
    "century-eastern-wonders": {"bgg_rating": 7.6, "bgg_weight": 2.18, "bgg_rank": 325, "num_ratings": 20000},
    "imhotep": {"bgg_rating": 7.1, "bgg_weight": 2.02, "bgg_rank": 545, "num_ratings": 28000},
    "ethnos": {"bgg_rating": 7.2, "bgg_weight": 2.05, "bgg_rank": 465, "num_ratings": 24000},
    "quest-for-el-dorado": {"bgg_rating": 7.5, "bgg_weight": 2.06, "bgg_rank": 215, "num_ratings": 38000},
    "downforce": {"bgg_rating": 7.2, "bgg_weight": 1.71, "bgg_rank": 585, "num_ratings": 16000},
    "flamme-rouge": {"bgg_rating": 7.5, "bgg_weight": 1.91, "bgg_rank": 245, "num_ratings": 28000},
    "jamaica": {"bgg_rating": 7.1, "bgg_weight": 1.78, "bgg_rank": 635, "num_ratings": 32000},
    "celestia": {"bgg_rating": 6.8, "bgg_weight": 1.25, "bgg_rank": 1450, "num_ratings": 14000},
    "treasure-island": {"bgg_rating": 7.4, "bgg_weight": 2.26, "bgg_rank": 445, "num_ratings": 14000},
    "survive-escape-from-atlantis": {"bgg_rating": 7.2, "bgg_weight": 1.64, "bgg_rank": 395, "num_ratings": 38000},
    "king-of-new-york": {"bgg_rating": 7.1, "bgg_weight": 2.1, "bgg_rank": 685, "num_ratings": 24000},
    "bunny-kingdom": {"bgg_rating": 7.4, "bgg_weight": 2.33, "bgg_rank": 325, "num_ratings": 24000},
    "isle-of-cats": {"bgg_rating": 7.6, "bgg_weight": 2.22, "bgg_rank": 185, "num_ratings": 32000},
    "nidavellir": {"bgg_rating": 7.6, "bgg_weight": 2.39, "bgg_rank": 195, "num_ratings": 24000},
    "its-a-wonderful-world": {"bgg_rating": 7.7, "bgg_weight": 2.26, "bgg_rank": 145, "num_ratings": 38000},
    "gizmos": {"bgg_rating": 7.2, "bgg_weight": 2.06, "bgg_rank": 465, "num_ratings": 28000},
    "space-base": {"bgg_rating": 7.4, "bgg_weight": 2.08, "bgg_rank": 305, "num_ratings": 28000},
    "cubitos": {"bgg_rating": 7.4, "bgg_weight": 2.12, "bgg_rank": 395, "num_ratings": 16000},
    "quartz": {"bgg_rating": 7.0, "bgg_weight": 1.42, "bgg_rank": 1250, "num_ratings": 8500},
    "libertalia-winds-of-galecrest": {"bgg_rating": 7.6, "bgg_weight": 2.22, "bgg_rank": 195, "num_ratings": 22000},
    "forgotten-waters": {"bgg_rating": 7.4, "bgg_weight": 2.18, "bgg_rank": 385, "num_ratings": 18000},
    "nemesis": {"bgg_rating": 8.1, "bgg_weight": 3.37, "bgg_rank": 32, "num_ratings": 52000},
    "eclipse-second-dawn": {"bgg_rating": 8.3, "bgg_weight": 3.68, "bgg_rank": 28, "num_ratings": 22000},
    "twilight-imperium-4": {"bgg_rating": 8.6, "bgg_weight": 4.24, "bgg_rank": 6, "num_ratings": 58000},
    "terra-mystica": {"bgg_rating": 8.2, "bgg_weight": 3.96, "bgg_rank": 17, "num_ratings": 95000},
    "gaia-project": {"bgg_rating": 8.4, "bgg_weight": 4.32, "bgg_rank": 10, "num_ratings": 62000},
    "feast-for-odin": {"bgg_rating": 8.2, "bgg_weight": 3.87, "bgg_rank": 18, "num_ratings": 48000},
    "le-havre": {"bgg_rating": 7.9, "bgg_weight": 3.77, "bgg_rank": 55, "num_ratings": 52000},
    "ora-et-labora": {"bgg_rating": 7.8, "bgg_weight": 3.99, "bgg_rank": 110, "num_ratings": 18000},
    "caverna": {"bgg_rating": 8.1, "bgg_weight": 3.78, "bgg_rank": 26, "num_ratings": 72000},
    "clans-of-caledonia": {"bgg_rating": 7.9, "bgg_weight": 3.38, "bgg_rank": 65, "num_ratings": 32000},
    "barrage": {"bgg_rating": 8.1, "bgg_weight": 4.05, "bgg_rank": 38, "num_ratings": 32000},
    "kanban-ev": {"bgg_rating": 8.2, "bgg_weight": 4.43, "bgg_rank": 45, "num_ratings": 14000},
    "lisboa": {"bgg_rating": 8.0, "bgg_weight": 4.52, "bgg_rank": 52, "num_ratings": 22000},
    "the-gallerist": {"bgg_rating": 8.0, "bgg_weight": 4.3, "bgg_rank": 68, "num_ratings": 18000},
    "anachrony": {"bgg_rating": 8.0, "bgg_weight": 4.08, "bgg_rank": 62, "num_ratings": 24000},
    "maracaibo": {"bgg_rating": 8.1, "bgg_weight": 3.77, "bgg_rank": 42, "num_ratings": 24000},
    "dune-imperium": {"bgg_rating": 8.4, "bgg_weight": 3.03, "bgg_rank": 9, "num_ratings": 82000},
    "oath": {"bgg_rating": 7.6, "bgg_weight": 4.11, "bgg_rank": 165, "num_ratings": 18000},
    "sleeping-gods": {"bgg_rating": 8.0, "bgg_weight": 3.24, "bgg_rank": 58, "num_ratings": 28000},
}

bgg.update(new_bgg)
save_json(bgg_path, bgg)
print(f"  bgg-metadata.json: {len(bgg)} games")


# ============================================================
# 4. GAME HIGHLIGHTS
# ============================================================
highlights_path = os.path.join(BASE, "content", "game-highlights.json")
highlights = load_json(highlights_path)

new_highlights = {
    "cant-stop": "Push your luck climbing numbered columns \u2014 one more roll could win it all or lose everything.",
    "jaipur": "Outwit your rival in a fast-paced market duel of camels, gems, and strategic trading.",
    "seven-wonders-duel": "Draft ancient wonders and outmaneuver your opponent in this perfect two-player civilization clash.",
    "santorini": "Build towers and invoke god powers in this beautiful abstract game of divine strategy.",
    "forbidden-island": "Race against rising tides to collect treasures before your island sanctuary sinks forever.",
    "forbidden-desert": "Survive scorching heat and shifting sands to uncover an ancient flying machine\u2019s lost parts.",
    "camel-up": "Bet on stacked racing camels in the wackiest, most unpredictable desert derby ever.",
    "sequence": "Connect five chips in a row using cards and cunning \u2014 simple to learn, endlessly strategic.",
    "blokus": "Claim territory with colorful pieces that must touch corners \u2014 elegant spatial puzzle warfare.",
    "unstable-unicorns": "Backstab your friends while building a magical unicorn army in this chaotic card game.",
    "exploding-kittens": "Defuse bombs and dodge disasters in a lightning-fast game of feline Russian roulette.",
    "machi-koro": "Roll dice to develop your city\u2019s economy \u2014 will you build bakeries or broadcast towers?",
    "tokaido": "Journey along a scenic Japanese road, collecting experiences in the most beautiful trip of your life.",
    "istanbul": "Navigate a bustling bazaar with your merchant and assistants to collect precious rubies first.",
    "five-tribes": "Manipulate colorful meeples across a desert marketplace in this brain-burning tactical puzzle.",
    "alhambra": "Construct the most magnificent palace complex using clever tile placement and currency management.",
    "karuba": "Race to guide your explorers through dense jungle paths to discover hidden temple treasures.",
    "kingsburg": "Influence advisors, gather resources, and defend your province from invading hordes each year.",
    "stone-age": "Feed your tribe, gather resources, and advance civilization from humble beginnings to prosperity.",
    "raiders-of-the-north-sea": "Assemble a Viking crew, raid settlements, and claim glory in this worker-placement adventure.",
    "architects-of-the-west-kingdom": "Build the kingdom\u2019s greatest structures while navigating corruption, taxes, and rival architects.",
    "paladins-of-the-west-kingdom": "Recruit townsfolk, go on quests, and battle to prove your devotion to the realm.",
    "champions-of-midgard": "Lead Viking warriors and mythical creatures against trolls, draugr, and fearsome monsters.",
    "clank-in-space": "Steal artifacts from an alien overlord\u2019s spaceship \u2014 but make too much noise and perish.",
    "mysterium-park": "A ghost sends cryptic visions to psychics investigating a mysterious carnival tragedy.",
    "horrified": "Unite to battle classic Universal Monsters \u2014 Dracula, the Mummy, and more threaten the town.",
    "unmatched": "Duel with iconic heroes from history and fiction in asymmetric tactical combat.",
    "dice-throne": "Roll dice, unleash abilities, and battle opponents in this fast-paced combat game.",
    "star-realms": "Build a space fleet and blast your opponent\u2019s authority to zero in this deckbuilding battle.",
    "hero-realms": "Fantasy deckbuilding combat where you recruit champions and cast spells to defeat rivals.",
    "res-arcana": "Master eight essences of magic to claim ancient monuments and power in this tight engine game.",
    "race-for-the-galaxy": "Build a galactic civilization through cards \u2014 explore, develop, settle, trade, and conquer.",
    "roll-for-the-galaxy": "Use dice workers to expand your space empire in this fast and colorful cosmic puzzle.",
    "pandemic-legacy-season-1": "Save humanity from disease in a year-long campaign where every choice permanently changes the game.",
    "gloomhaven-jaws-of-the-lion": "Tactical mercenary adventures with evolving characters \u2014 dungeon crawling without the dungeon master.",
    "mice-and-mystics": "Brave mice battle cats and rats in a storybook adventure to save the kingdom.",
    "descent-legends-of-the-dark": "Epic fantasy quests powered by an app that controls enemies and tells branching stories.",
    "mansions-of-madness": "Investigate eldritch mysteries in a fully narrated horror adventure where madness lurks everywhere.",
    "arkham-horror-card-game": "Build investigator decks and unravel cosmic conspiracies in this narrative card adventure.",
    "marvel-champions": "Become iconic Marvel heroes and thwart villainous schemes in cooperative deckbuilding battles.",
    "keyforge": "Every deck is unique \u2014 master the cards you\u2019re dealt in this innovative combat game.",
    "aeons-end": "Mages cooperate to defend the last city from interdimensional Nameless horrors using spell combos.",
    "tiny-towns": "Draft resources to build the cutest town \u2014 limited space means every placement matters hugely.",
    "calico": "Sew a cozy quilt that attracts cats and buttons in this delightful spatial puzzle.",
    "cascadia": "Create thriving Pacific Northwest habitats by drafting tiles and pairing them with wildlife.",
    "harmonies": "Build harmonious landscapes where animals and elements interact in colorful, peaceful patterns.",
    "sky-team": "Pilot and copilot must land the plane using dice \u2014 communicate only through actions, not words.",
    "meadow": "Wander through nature collecting memories and wildlife in a serene, contemplative journey.",
    "flamecraft": "Gather adorable dragons to help your shops flourish in a charming town of artisan magic.",
    "my-city": "Build your personal city across a 24-game legacy campaign \u2014 mistakes become permanent features.",
    "cryptid": "One clue each \u2014 deduce where the cryptid hides through logic and careful questioning of rivals.",
    "deception-murder-in-hong-kong": "A silent forensic scientist guides detectives to identify the killer among them through cryptic clues.",
    "blood-on-the-clocktower": "Even dead players influence this social deduction game of demonic deception and town chaos.",
    "secret-hitler": "Liberals vs. Fascists in a game of lies, accusations, and desperate trust decisions.",
    "the-resistance-avalon": "Find Merlin and the loyal servants while spies sabotage quests in this bluffing battle.",
    "werewords": "Guess the secret word while deducing which player is the werewolf feeding you false information.",
    "a-fake-artist-goes-to-new-york": "Everyone draws the same thing \u2014 except the fake artist who\u2019s desperately improvising.",
    "monikers": "Describe, act out, and one-word clue ridiculous names across three hilarious rounds.",
    "taboo": "Get teammates to say the word without using the five obvious clues listed below it.",
    "scattergories": "Think fast and creative \u2014 list unique words starting with one letter across random categories.",
    "apples-to-apples": "Match noun cards to adjectives in this simple, silly comparison party game.",
    "what-do-you-meme": "Caption photos with outrageous phrases in this internet culture comedy competition.",
    "cards-against-humanity": "Fill in offensive blanks with horrible cards \u2014 the most inappropriate answer wins.",
    "jenga": "Carefully remove wooden blocks from a tower until someone makes it all come crashing down.",
    "connect-four": "Drop checkers to connect four in a row \u2014 simple rules hide surprising tactical depth.",
    "boggle": "Shake the grid and race to find words in a timed jumble of lettered dice.",
    "bananagrams": "Everyone builds their own crossword simultaneously \u2014 no turns, just frantic word-forming speed.",
    "scrabble": "Form high-scoring words on a crossword board using letter tiles and strategic placement.",
    "trivial-pursuit": "Answer trivia across six categories to fill your pie and prove your general knowledge mastery.",
    "clue": "Deduce who killed Mr. Boddy, with what weapon, and in which room through logic and luck.",
    "monopoly": "Buy properties, charge rent, and bankrupt opponents in this classic real estate trading game.",
    "risk": "Command armies and conquer territories in a globe-spanning battle for world domination.",
    "chess": "Command an army of pieces with unique moves in humanity\u2019s timeless strategy masterpiece.",
    "checkers": "Jump opponent pieces and reach the far side to crown your kings in this classic game.",
    "backgammon": "Race your checkers home while blocking opponents in this ancient game of dice and tactics.",
    "mahjong": "Match beautiful tiles to form winning patterns in this traditional Chinese game of skill.",
    "cribbage": "Peg your way to 121 points through clever card combinations and strategic counting.",
    "gin-rummy": "Form melds and minimize deadwood to knock and win in this classic two-player card game.",
    "uno": "Match colors and numbers while deploying wild cards and skips to be first to empty your hand.",
    "skip-bo": "Build sequential stacks from your personal pile \u2014 first to empty it wins this wild race.",
    "phase-10": "Complete ten different card-collecting challenges before opponents finish theirs in this rummy variant.",
    "ticket-to-ride-europe": "Claim railway routes across Europe with tunnels, ferries, and station strategy twists.",
    "ticket-to-ride-nordic": "Connect Scandinavian cities in a tighter, more cutthroat take on the railway classic.",
    "catan-seafarers": "Expand Catan beyond the original island by building ships and discovering new territories to settle.",
    "pandemic-hot-zone": "Contain diseases threatening a single region in this streamlined, faster Pandemic experience.",
    "codenames-duet": "Two spies cooperate to identify all agents using one-word clues and careful deduction.",
    "sushi-go": "Draft adorable sushi cards for tasty scoring combos in this fast and charming card game.",
    "love-letter-2019": "Win the princess\u2019s heart by delivering your letter using deduction and risky card plays.",
    "the-mind": "Play cards in ascending order without speaking \u2014 pure telepathy and timing synchronization required.",
    "hanabi": "Cooperatively build fireworks displays while only seeing everyone else\u2019s cards, not your own.",
    "point-salad": "Draft vegetables and scoring cards to build the ultimate salad \u2014 simple, quick, and addictive.",
    "no-thanks": "Bid chips to avoid taking cards \u2014 sometimes the points you don\u2019t take matter most.",
    "take-5": "Play numbered cards to avoid being the sixth in a row and taking penalty points.",
    "scout": "Play cards from your hand\u2019s ends only \u2014 or scout opponents\u2019 plays in this combo challenge.",
    "cockroach-poker": "Bluff about disgusting critters you\u2019re passing to opponents \u2014 get caught four times and lose.",
    "fox-in-the-forest": "Win tricks but not too many in this clever two-player fairy tale card game.",
    "hanamikoji": "Win the favor of geishas through careful card play and agonizing strategic sacrifices.",
    "lost-cities-card-game": "Launch risky expeditions with ascending cards \u2014 invest early or play it safe for points?",
    "schotten-totten": "Form poker-style combinations to claim boundary stones in this intense two-player duel.",
    "onitama": "Outwit your opponent using martial arts move cards that shift between players each turn.",
    "hive": "Surround the enemy queen bee with your insect army in this chess-like game without a board.",
    "azul-summer-pavilion": "Draft colorful tiles to decorate a summer palace with symmetrical beauty and clever timing.",
    "azul-stained-glass": "Carefully select glass panes to create the most stunning cathedral window patterns possible.",
    "splendor-duel": "Collect gems and pearls to claim prestige in a head-to-head jewel market confrontation.",
    "century-eastern-wonders": "Sail island trade routes, build markets, and deliver exotic spices for profit and fame.",
    "imhotep": "Load stones onto boats sailing to monuments \u2014 but opponents decide where those boats dock.",
    "ethnos": "Recruit fantasy races and control kingdoms through clever hand management and timing your reveals.",
    "quest-for-el-dorado": "Deckbuild your way through the jungle, racing rivals to discover the legendary golden city.",
    "downforce": "Bid on cars, race them around a track, and bet on winners in this high-speed betting game.",
    "flamme-rouge": "Manage cyclist exhaustion and slipstream behind rivals in this tense Tour de France race.",
    "jamaica": "Pirate ships race around an island, battling and stealing treasure in this swashbuckling adventure.",
    "celestia": "Push your luck flying to cloud cities \u2014 bail early for safe points or risk crashing dramatically.",
    "treasure-island": "One player is Long John Silver, leaving cryptic clues while others race to dig up hidden treasure.",
    "survive-escape-from-atlantis": "Rescue your people from a sinking island while sea monsters and sharks hunt them down.",
    "king-of-new-york": "Giant monsters rampage through NYC, smashing buildings and battling for ultimate supremacy.",
    "bunny-kingdom": "Draft cards to expand your rabbit empire across a colorful map and build towering cities.",
    "isle-of-cats": "Draft polyomino cats to fill your boat \u2014 rescue the most valuable felines before evil arrives.",
    "nidavellir": "Bid coins to recruit dwarves and form tavern coalitions in this clever auction and drafting game.",
    "its-a-wonderful-world": "Draft cards and build an empire engine that snowballs into glorious production combos.",
    "gizmos": "Build a marble-powered research engine that triggers spectacular chains of scientific advancement.",
    "space-base": "Roll dice to activate ships in your tableau \u2014 benefit even on opponents\u2019 turns in this engine builder.",
    "cubitos": "Race cube-pushing robots by upgrading your dice pool and unleashing powerful ability combinations.",
    "quartz": "Push your luck mining gems in unstable caverns \u2014 take too many crystals and lose everything.",
    "libertalia-winds-of-galecrest": "Draft and play pirate crew simultaneously, predicting rivals\u2019 moves for treasure and glory.",
    "forgotten-waters": "Swashbuckling pirate stories with branching narratives, disasters, and ridiculous personality-driven chaos.",
    "nemesis": "Survive aboard an alien-infested ship where crewmates might have secret agendas and betrayals.",
    "eclipse-second-dawn": "Explore space, research technology, and wage epic fleet battles for galactic domination.",
    "twilight-imperium-4": "Negotiate, battle, and scheme your way to control the galaxy in this legendary space opera.",
    "terra-mystica": "Transform terrain and expand your asymmetric faction across a contested world of strategic depth.",
    "gaia-project": "Terraform planets and research alien technologies in this brain-burning space civilization puzzle.",
    "feast-for-odin": "Viking life simulation \u2014 raid, craft, farm, and hunt to fill your boards with prosperous goods.",
    "le-havre": "Build and use buildings to process resources into wealth in this economic engine masterpiece.",
    "ora-et-labora": "Monks pray, work, and build monasteries using resources and clever production chain management.",
    "caverna": "Dig mountain caves, raise animals, and farm fields in this open-ended dwarven sandbox adventure.",
    "clans-of-caledonia": "Trade whisky and cheese across Scotland while managing resources and expanding your clan\u2019s reach.",
    "barrage": "Engineer massive dams and control water flow to power turbines in this ruthless resource war.",
    "kanban-ev": "Manage a car factory\u2019s departments to impress Sandra, the demanding board administrator, with efficiency.",
    "lisboa": "Rebuild Lisbon after the devastating 1755 earthquake through politics, commerce, and careful planning.",
    "the-gallerist": "Discover artists, promote them, and sell masterpieces in the cutthroat contemporary art market.",
    "anachrony": "Time-traveling factions compete to save humanity while paradoxes threaten to unravel reality itself.",
    "maracaibo": "Sail the Caribbean, deliver goods, complete quests, and influence nations in this story-driven adventure.",
    "dune-imperium": "Combine deckbuilding and worker placement to control spice, forge alliances, and dominate Arrakis.",
    "oath": "Shape a kingdom\u2019s chronicle across games where today\u2019s victor becomes tomorrow\u2019s established power.",
    "sleeping-gods": "Captain a steamship across a vast open world, making choices in a persistent narrative adventure.",
}

highlights.update(new_highlights)
save_json(highlights_path, highlights)
print(f"  game-highlights.json: {len(highlights)} games")

print(f"\nAll metadata merged successfully!")
