-- Thai House step image attachments
-- Generated by build_thaihouse_sql.py

-- catan: 4 images -> walk[9] sum[9]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('catan-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('catan-setup-01-components.jpg'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,3,image}', to_jsonb('catan-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,3,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,3,image}', to_jsonb('catan-setup-02-board-setup.jpg'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,5,image}', to_jsonb('catan-setup-03-player-area.jpg'::text)), '{setup,walkthrough,5,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,5,image}', to_jsonb('catan-setup-03-player-area.jpg'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,8,image}', to_jsonb('catan-setup-04-tokens-cards.jpg'::text)), '{setup,walkthrough,8,image_caption}', to_jsonb('Tokens, cards, and key components'::text)) WHERE game_id = 'catan';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,8,image}', to_jsonb('catan-setup-04-tokens-cards.jpg'::text)) WHERE game_id = 'catan';


-- wingspan: handled separately via local JSON sync, SKIPPED
-- azul: 2 images -> walk[7] sum[7]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('azul-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'azul';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('azul-setup-01-components.jpg'::text)) WHERE game_id = 'azul';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,6,image}', to_jsonb('azul-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,6,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'azul';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,6,image}', to_jsonb('azul-setup-02-board-setup.jpg'::text)) WHERE game_id = 'azul';


-- splendor: 1 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('splendor-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'splendor';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('splendor-setup-01-components.jpg'::text)) WHERE game_id = 'splendor';


-- ticket-to-ride: 8 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('ticket-to-ride-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('ticket-to-ride-setup-01-components.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,1,image}', to_jsonb('ticket-to-ride-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,1,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,1,image}', to_jsonb('ticket-to-ride-setup-02-board-setup.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('ticket-to-ride-setup-03-player-area.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('ticket-to-ride-setup-03-player-area.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,3,image}', to_jsonb('ticket-to-ride-setup-04-tokens-cards.jpg'::text)), '{setup,walkthrough,3,image_caption}', to_jsonb('Tokens, cards, and key components'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,3,image}', to_jsonb('ticket-to-ride-setup-04-tokens-cards.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,4,image}', to_jsonb('ticket-to-ride-setup-05-setup-detail.jpg'::text)), '{setup,walkthrough,4,image_caption}', to_jsonb('Setup detail view'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,4,image}', to_jsonb('ticket-to-ride-setup-05-setup-detail.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,5,image}', to_jsonb('ticket-to-ride-setup-06-mid-setup.jpg'::text)), '{setup,walkthrough,5,image_caption}', to_jsonb('Mid-setup checkpoint'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,5,image}', to_jsonb('ticket-to-ride-setup-06-mid-setup.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,6,image}', to_jsonb('ticket-to-ride-setup-07-late-setup.jpg'::text)), '{setup,walkthrough,6,image_caption}', to_jsonb('Late-setup checkpoint'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,6,image}', to_jsonb('ticket-to-ride-setup-07-late-setup.jpg'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,7,image}', to_jsonb('ticket-to-ride-setup-08-final-setup.jpg'::text)), '{setup,walkthrough,7,image_caption}', to_jsonb('Final setup - your table should look like this'::text)) WHERE game_id = 'ticket-to-ride';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,7,image}', to_jsonb('ticket-to-ride-setup-08-final-setup.jpg'::text)) WHERE game_id = 'ticket-to-ride';


-- exploding-kittens: 1 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('exploding-kittens-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'exploding-kittens';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('exploding-kittens-setup-01-components.jpg'::text)) WHERE game_id = 'exploding-kittens';


-- codenames: 2 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('codenames-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'codenames';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('codenames-setup-01-components.jpg'::text)) WHERE game_id = 'codenames';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,5,image}', to_jsonb('codenames-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,5,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'codenames';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,5,image}', to_jsonb('codenames-setup-02-board-setup.jpg'::text)) WHERE game_id = 'codenames';


-- king-of-tokyo: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('king-of-tokyo-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'king-of-tokyo';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('king-of-tokyo-setup-01-components.jpg'::text)) WHERE game_id = 'king-of-tokyo';


-- pandemic: 2 images -> walk[13] sum[13]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('pandemic-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'pandemic';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('pandemic-setup-01-components.jpg'::text)) WHERE game_id = 'pandemic';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,12,image}', to_jsonb('pandemic-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,12,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'pandemic';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,12,image}', to_jsonb('pandemic-setup-02-board-setup.jpg'::text)) WHERE game_id = 'pandemic';


-- everdell: 2 images -> walk[14] sum[14]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('everdell-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'everdell';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('everdell-setup-01-components.jpg'::text)) WHERE game_id = 'everdell';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,13,image}', to_jsonb('everdell-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,13,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'everdell';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,13,image}', to_jsonb('everdell-setup-02-board-setup.jpg'::text)) WHERE game_id = 'everdell';


-- carcassonne: 1 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('carcassonne-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'carcassonne';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('carcassonne-setup-01-components.jpg'::text)) WHERE game_id = 'carcassonne';


-- dixit: 5 images -> walk[5] sum[5]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('dixit-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('dixit-setup-01-components.jpg'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,1,image}', to_jsonb('dixit-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,1,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,1,image}', to_jsonb('dixit-setup-02-board-setup.jpg'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('dixit-setup-03-player-area.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('dixit-setup-03-player-area.jpg'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,3,image}', to_jsonb('dixit-setup-04-tokens-cards.jpg'::text)), '{setup,walkthrough,3,image_caption}', to_jsonb('Tokens, cards, and key components'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,3,image}', to_jsonb('dixit-setup-04-tokens-cards.jpg'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,4,image}', to_jsonb('dixit-setup-05-setup-detail.jpg'::text)), '{setup,walkthrough,4,image_caption}', to_jsonb('Setup detail view'::text)) WHERE game_id = 'dixit';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,4,image}', to_jsonb('dixit-setup-05-setup-detail.jpg'::text)) WHERE game_id = 'dixit';


-- sushi-go: 1 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('sushi-go-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'sushi-go';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('sushi-go-setup-01-components.jpg'::text)) WHERE game_id = 'sushi-go';


-- seven-wonders: 6 images -> walk[10] sum[10]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('seven-wonders-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('seven-wonders-setup-01-components.jpg'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('seven-wonders-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('seven-wonders-setup-02-board-setup.jpg'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,4,image}', to_jsonb('seven-wonders-setup-03-player-area.jpg'::text)), '{setup,walkthrough,4,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,4,image}', to_jsonb('seven-wonders-setup-03-player-area.jpg'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,5,image}', to_jsonb('seven-wonders-setup-04-tokens-cards.jpg'::text)), '{setup,walkthrough,5,image_caption}', to_jsonb('Tokens, cards, and key components'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,5,image}', to_jsonb('seven-wonders-setup-04-tokens-cards.jpg'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,7,image}', to_jsonb('seven-wonders-setup-05-setup-detail.jpg'::text)), '{setup,walkthrough,7,image_caption}', to_jsonb('Setup detail view'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,7,image}', to_jsonb('seven-wonders-setup-05-setup-detail.jpg'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,9,image}', to_jsonb('seven-wonders-setup-06-mid-setup.jpg'::text)), '{setup,walkthrough,9,image_caption}', to_jsonb('Mid-setup checkpoint'::text)) WHERE game_id = 'seven-wonders';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,9,image}', to_jsonb('seven-wonders-setup-06-mid-setup.jpg'::text)) WHERE game_id = 'seven-wonders';


-- flamecraft: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('flamecraft-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'flamecraft';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('flamecraft-setup-01-components.jpg'::text)) WHERE game_id = 'flamecraft';


-- cant-stop: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('cant-stop-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'cant-stop';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('cant-stop-setup-01-components.jpg'::text)) WHERE game_id = 'cant-stop';


-- cant-stop-korean: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('cant-stop-korean-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'cant-stop-korean';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('cant-stop-korean-setup-01-components.jpg'::text)) WHERE game_id = 'cant-stop-korean';


-- century-golem-edition: 1 images -> walk[9] sum[9]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('century-golem-edition-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'century-golem-edition';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('century-golem-edition-setup-01-components.jpg'::text)) WHERE game_id = 'century-golem-edition';


-- machi-koro: 1 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('machi-koro-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'machi-koro';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('machi-koro-setup-01-components.jpg'::text)) WHERE game_id = 'machi-koro';


-- one-night-ultimate-werewolf: 4 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('one-night-ultimate-werewolf-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('one-night-ultimate-werewolf-setup-01-components.jpg'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,1,image}', to_jsonb('one-night-ultimate-werewolf-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,1,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,1,image}', to_jsonb('one-night-ultimate-werewolf-setup-02-board-setup.jpg'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('one-night-ultimate-werewolf-setup-03-player-area.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('one-night-ultimate-werewolf-setup-03-player-area.jpg'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,3,image}', to_jsonb('one-night-ultimate-werewolf-setup-04-tokens-cards.jpg'::text)), '{setup,walkthrough,3,image_caption}', to_jsonb('Tokens, cards, and key components'::text)) WHERE game_id = 'one-night-ultimate-werewolf';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,3,image}', to_jsonb('one-night-ultimate-werewolf-setup-04-tokens-cards.jpg'::text)) WHERE game_id = 'one-night-ultimate-werewolf';


-- codenames-duet: 2 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('codenames-duet-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'codenames-duet';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('codenames-duet-setup-01-components.jpg'::text)) WHERE game_id = 'codenames-duet';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,3,image}', to_jsonb('codenames-duet-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,3,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'codenames-duet';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,3,image}', to_jsonb('codenames-duet-setup-02-board-setup.jpg'::text)) WHERE game_id = 'codenames-duet';


-- codenames-pictures-heirloom-edition: 2 images -> walk[7] sum[7]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('codenames-pictures-heirloom-edition-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'codenames-pictures-heirloom-edition';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('codenames-pictures-heirloom-edition-setup-01-components.jpg'::text)) WHERE game_id = 'codenames-pictures-heirloom-edition';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,6,image}', to_jsonb('codenames-pictures-heirloom-edition-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,6,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'codenames-pictures-heirloom-edition';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,6,image}', to_jsonb('codenames-pictures-heirloom-edition-setup-02-board-setup.jpg'::text)) WHERE game_id = 'codenames-pictures-heirloom-edition';


-- wavelength: 1 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('wavelength-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'wavelength';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('wavelength-setup-01-components.jpg'::text)) WHERE game_id = 'wavelength';


-- secret-hitler: 1 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('secret-hitler-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'secret-hitler';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('secret-hitler-setup-01-components.jpg'::text)) WHERE game_id = 'secret-hitler';


-- scattergories: 1 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('scattergories-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'scattergories';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('scattergories-setup-01-components.jpg'::text)) WHERE game_id = 'scattergories';


-- love-letter: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('love-letter-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'love-letter';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('love-letter-setup-01-components.jpg'::text)) WHERE game_id = 'love-letter';


-- spot-it: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('spot-it-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'spot-it';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('spot-it-setup-01-components.jpg'::text)) WHERE game_id = 'spot-it';


-- six-nimmt: 1 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('six-nimmt-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'six-nimmt';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('six-nimmt-setup-01-components.jpg'::text)) WHERE game_id = 'six-nimmt';


-- the-crew: 1 images -> walk[5] sum[5]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('the-crew-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'the-crew';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('the-crew-setup-01-components.jpg'::text)) WHERE game_id = 'the-crew';


-- deception-murder-in-hong-kong: 1 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('deception-murder-in-hong-kong-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'deception-murder-in-hong-kong';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('deception-murder-in-hong-kong-setup-01-components.jpg'::text)) WHERE game_id = 'deception-murder-in-hong-kong';


-- uno: 3 images -> walk[4] sum[4]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('uno-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'uno';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('uno-setup-01-components.jpg'::text)) WHERE game_id = 'uno';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('uno-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'uno';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('uno-setup-02-board-setup.jpg'::text)) WHERE game_id = 'uno';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,3,image}', to_jsonb('uno-setup-03-player-area.jpg'::text)), '{setup,walkthrough,3,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'uno';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,3,image}', to_jsonb('uno-setup-03-player-area.jpg'::text)) WHERE game_id = 'uno';


-- clue: 3 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('clue-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'clue';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('clue-setup-01-components.jpg'::text)) WHERE game_id = 'clue';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('clue-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'clue';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('clue-setup-02-board-setup.jpg'::text)) WHERE game_id = 'clue';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,5,image}', to_jsonb('clue-setup-03-player-area.jpg'::text)), '{setup,walkthrough,5,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'clue';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,5,image}', to_jsonb('clue-setup-03-player-area.jpg'::text)) WHERE game_id = 'clue';


-- rummikub: 3 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('rummikub-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'rummikub';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('rummikub-setup-01-components.jpg'::text)) WHERE game_id = 'rummikub';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('rummikub-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'rummikub';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('rummikub-setup-02-board-setup.jpg'::text)) WHERE game_id = 'rummikub';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,5,image}', to_jsonb('rummikub-setup-03-player-area.jpg'::text)), '{setup,walkthrough,5,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'rummikub';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,5,image}', to_jsonb('rummikub-setup-03-player-area.jpg'::text)) WHERE game_id = 'rummikub';


-- tokaido: 1 images -> walk[7] sum[7]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('tokaido-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'tokaido';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('tokaido-setup-01-components.jpg'::text)) WHERE game_id = 'tokaido';


-- century-golem-edition-endless-world: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('century-golem-edition-endless-world-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'century-golem-edition-endless-world';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('century-golem-edition-endless-world-setup-01-components.jpg'::text)) WHERE game_id = 'century-golem-edition-endless-world';


-- risk-game-of-thrones: 2 images -> walk[7] sum[7]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('risk-game-of-thrones-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'risk-game-of-thrones';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('risk-game-of-thrones-setup-01-components.jpg'::text)) WHERE game_id = 'risk-game-of-thrones';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,6,image}', to_jsonb('risk-game-of-thrones-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,6,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'risk-game-of-thrones';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,6,image}', to_jsonb('risk-game-of-thrones-setup-02-board-setup.jpg'::text)) WHERE game_id = 'risk-game-of-thrones';


-- welcome-to: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('welcome-to-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'welcome-to';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('welcome-to-setup-01-components.jpg'::text)) WHERE game_id = 'welcome-to';


-- above-and-below: 8 images -> walk[14] sum[14]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('above-and-below-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('above-and-below-setup-01-components.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,2,image}', to_jsonb('above-and-below-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,2,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,2,image}', to_jsonb('above-and-below-setup-02-board-setup.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,4,image}', to_jsonb('above-and-below-setup-03-player-area.jpg'::text)), '{setup,walkthrough,4,image_caption}', to_jsonb('Player starting area'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,4,image}', to_jsonb('above-and-below-setup-03-player-area.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,6,image}', to_jsonb('above-and-below-setup-04-tokens-cards.jpg'::text)), '{setup,walkthrough,6,image_caption}', to_jsonb('Tokens, cards, and key components'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,6,image}', to_jsonb('above-and-below-setup-04-tokens-cards.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,7,image}', to_jsonb('above-and-below-setup-05-setup-detail.jpg'::text)), '{setup,walkthrough,7,image_caption}', to_jsonb('Setup detail view'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,7,image}', to_jsonb('above-and-below-setup-05-setup-detail.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,9,image}', to_jsonb('above-and-below-setup-06-mid-setup.jpg'::text)), '{setup,walkthrough,9,image_caption}', to_jsonb('Mid-setup checkpoint'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,9,image}', to_jsonb('above-and-below-setup-06-mid-setup.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,11,image}', to_jsonb('above-and-below-setup-07-late-setup.jpg'::text)), '{setup,walkthrough,11,image_caption}', to_jsonb('Late-setup checkpoint'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,11,image}', to_jsonb('above-and-below-setup-07-late-setup.jpg'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,13,image}', to_jsonb('above-and-below-setup-08-final-setup.jpg'::text)), '{setup,walkthrough,13,image_caption}', to_jsonb('Final setup - your table should look like this'::text)) WHERE game_id = 'above-and-below';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,13,image}', to_jsonb('above-and-below-setup-08-final-setup.jpg'::text)) WHERE game_id = 'above-and-below';


-- quacks-of-quedlinburg: 1 images -> walk[12] sum[12]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('quacks-of-quedlinburg-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'quacks-of-quedlinburg';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('quacks-of-quedlinburg-setup-01-components.jpg'::text)) WHERE game_id = 'quacks-of-quedlinburg';


-- betrayal-at-house-on-the-hill: 2 images -> walk[10] sum[10]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('betrayal-at-house-on-the-hill-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'betrayal-at-house-on-the-hill';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('betrayal-at-house-on-the-hill-setup-01-components.jpg'::text)) WHERE game_id = 'betrayal-at-house-on-the-hill';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,9,image}', to_jsonb('betrayal-at-house-on-the-hill-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,9,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'betrayal-at-house-on-the-hill';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,9,image}', to_jsonb('betrayal-at-house-on-the-hill-setup-02-board-setup.jpg'::text)) WHERE game_id = 'betrayal-at-house-on-the-hill';


-- dead-of-winter: 1 images -> walk[14] sum[14]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('dead-of-winter-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'dead-of-winter';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('dead-of-winter-setup-01-components.jpg'::text)) WHERE game_id = 'dead-of-winter';


-- villainous: 1 images -> walk[10] sum[10]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('villainous-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'villainous';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('villainous-setup-01-components.jpg'::text)) WHERE game_id = 'villainous';


-- sheriff-of-nottingham: 1 images -> walk[10] sum[10]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('sheriff-of-nottingham-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'sheriff-of-nottingham';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('sheriff-of-nottingham-setup-01-components.jpg'::text)) WHERE game_id = 'sheriff-of-nottingham';


-- everdell-pearlbrook: 2 images -> walk[8] sum[8]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('everdell-pearlbrook-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'everdell-pearlbrook';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('everdell-pearlbrook-setup-01-components.jpg'::text)) WHERE game_id = 'everdell-pearlbrook';
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,7,image}', to_jsonb('everdell-pearlbrook-setup-02-board-setup.jpg'::text)), '{setup,walkthrough,7,image_caption}', to_jsonb('Initial board setup'::text)) WHERE game_id = 'everdell-pearlbrook';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,7,image}', to_jsonb('everdell-pearlbrook-setup-02-board-setup.jpg'::text)) WHERE game_id = 'everdell-pearlbrook';


-- takenoko: 1 images -> walk[10] sum[10]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('takenoko-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'takenoko';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('takenoko-setup-01-components.jpg'::text)) WHERE game_id = 'takenoko';


-- scythe: 1 images -> walk[12] sum[12]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('scythe-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'scythe';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('scythe-setup-01-components.jpg'::text)) WHERE game_id = 'scythe';


-- root: 1 images -> walk[15] sum[15]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('root-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'root';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('root-setup-01-components.jpg'::text)) WHERE game_id = 'root';


-- exit-the-game-series: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('exit-the-game-series-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'exit-the-game-series';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('exit-the-game-series-setup-01-components.jpg'::text)) WHERE game_id = 'exit-the-game-series';


-- 5-minute-dungeon: 1 images -> walk[7] sum[7]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('5-minute-dungeon-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = '5-minute-dungeon';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('5-minute-dungeon-setup-01-components.jpg'::text)) WHERE game_id = '5-minute-dungeon';


-- 5-minute-mystery: 1 images -> walk[7] sum[7]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('5-minute-mystery-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = '5-minute-mystery';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('5-minute-mystery-setup-01-components.jpg'::text)) WHERE game_id = '5-minute-mystery';


-- unlock-escape-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-escape-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-escape-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-escape-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-escape-adventures';


-- unlock-mystery-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-mystery-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-mystery-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-mystery-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-mystery-adventures';


-- unlock-secret-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-secret-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-secret-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-secret-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-secret-adventures';


-- unlock-exotic-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-exotic-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-exotic-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-exotic-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-exotic-adventures';


-- unlock-timeless-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-timeless-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-timeless-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-timeless-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-timeless-adventures';


-- unlock-epic-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-epic-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-epic-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-epic-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-epic-adventures';


-- unlock-mythic-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-mythic-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-mythic-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-mythic-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-mythic-adventures';


-- unlock-game-adventures: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-game-adventures-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-game-adventures';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-game-adventures-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-game-adventures';


-- unlock-star-wars-escape-game: 1 images -> walk[6] sum[6]
UPDATE games SET teaching = jsonb_set(jsonb_set(teaching, '{setup,walkthrough,0,image}', to_jsonb('unlock-star-wars-escape-game-setup-01-components.jpg'::text)), '{setup,walkthrough,0,image_caption}', to_jsonb('Game components and starting layout'::text)) WHERE game_id = 'unlock-star-wars-escape-game';
UPDATE games SET teaching = jsonb_set(teaching, '{setup,summary,0,image}', to_jsonb('unlock-star-wars-escape-game-setup-01-components.jpg'::text)) WHERE game_id = 'unlock-star-wars-escape-game';

